/**
 * @module feature
 * @description Feature Development Workflow — 7 steps.
 *   (1) Analyze requirements, (2) Present plan for approval (HITL),
 *   (3) Parallel layer agents (DB/backend/frontend), (4) Integrate,
 *   (5) Run tests, (6) Quality review, (7) Generate commit messages.
 */

import type { WorkflowDefinition } from '../../types';

export const FEATURE_WORKFLOW: WorkflowDefinition = {
  id: 'feature',
  name: 'Feature Development',
  steps: [
    {
      id: 'interview-requirements',
      name: 'Interviewing for requirements',
      type: 'agent' as const,
      agentRole: 'interviewer',
      modelTier: 'standard',
      toolScope: 'research',
      timeoutMs: 180_000,  // 3 min for full interview loop
      maxRetries: 0,
      promptTemplate: '',  // Placeholder, not used for interviewer agents
      contextScope: 'full' as const,
    } as any,
    {
      id: 'present-plan',
      name: 'Presenting plan for approval',
      type: 'sequential',
      agentRole: 'planner',
      modelTier: 'free',
      toolScope: 'research',
      contextScope: 'full',
      requiresApproval: true,
      promptTemplate: `You are a technical planner. Create a detailed execution plan.\n\nApplication Context:\n{app_context}\n\nFeature Request:\n{user_request}\n\nCreate a plan with:\n- Database Layer (schema changes, migrations)\n- Backend Layer (endpoints, business logic)\n- Frontend Layer (components, state)\n- Timeline Estimate\n- Risks & Assumptions`,
      timeoutMs: 45_000,
      maxRetries: 2,
    },
    {
      id: 'parallel-agents',
      name: 'Delegating to layer agents',
      type: 'parallel',
      agentRole: 'planner',
      modelTier: 'free',
      toolScope: 'implementation',
      promptTemplate: 'Execute the approved plan for your layer.',
      timeoutMs: 120_000,
      maxRetries: 2,
      branches: [
        {
          id: 'design-database',
          name: 'Designing database schema',
          type: 'agent' as const,
          agentRole: 'database',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
        {
          id: 'implement-backend',
          name: 'Implementing backend API',
          type: 'agent' as const,
          agentRole: 'backend',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
        {
          id: 'build-frontend',
          name: 'Building frontend UI',
          type: 'agent' as const,
          agentRole: 'frontend',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
      ],
    },
    {
      id: 'integrate-layers',
      name: 'Integrating layers',
      type: 'sequential',
      agentRole: 'fixer',
      modelTier: 'free',
      toolScope: 'implementation',
      contextScope: 'patterns',
      promptTemplate: `Integrate the outputs from all three layer agents.\n\nLayer outputs:\n{previous_output}\n\nEnsure imports are correct, types align, and the feature works end-to-end.`,
      timeoutMs: 60_000,
      maxRetries: 1,
    },
    {
      id: 'run-tests',
      name: 'Running tests',
      type: 'sequential',
      agentRole: 'fixer',
      modelTier: 'free',
      toolScope: 'implementation',
      contextScope: 'commands',
      promptTemplate: 'Run the project test suite to verify the feature works.\n\nTest command: {test_command}',
      timeoutMs: 300_000,
      maxRetries: 0,
    },
    {
      id: 'quality-review',
      name: 'Quality review',
      type: 'sequential',
      agentRole: 'quality_reviewer',
      modelTier: 'standard',
      toolScope: 'review',
      contextScope: 'patterns',
      promptTemplate: `Review the implemented feature for quality, security, and performance.\n\nChanges:\n{previous_output}\n\nCheck for:\n1. Security issues\n2. Performance concerns\n3. Code quality\n4. Test coverage gaps`,
      timeoutMs: 60_000,
      maxRetries: 1,
    },
    {
      id: 'generate-commits',
      name: 'Generating commit messages',
      type: 'sequential',
      agentRole: 'documentarian',
      modelTier: 'free',
      toolScope: 'research',
      contextScope: 'stack',
      promptTemplate: `Generate commit messages for the feature implementation.\n\nChanges summary:\n{previous_output}\n\nUse conventional commits format (feat:, fix:, etc.).`,
      timeoutMs: 15_000,
      maxRetries: 0,
    },
  ],
};
