/**
 * @module feature
 * @description Feature Development Workflow — 8 steps.
 *   Follows the EPIC methodology: (1-2) Explore, (3) Plan, (4) TDD, (5-6) Implement,
 *   (7) Quality Review, (8) Commit.
 */

import type { WorkflowDefinition } from '../../types';

export const FEATURE_WORKFLOW: WorkflowDefinition = {
  id: 'feature',
  name: 'Feature Development (EPIC)',
  steps: [
    {
      id: 'explore-requirements',
      name: 'Exploring requirements (Read-Only)',
      type: 'agent' as const,
      agentRole: 'project_analyzer',
      modelTier: 'standard',
      toolScope: 'research',
      timeoutMs: 180_000,
      maxRetries: 0,
      contextScope: 'full' as const,
    } as any,
    {
      id: 'present-plan',
      name: 'Presenting plan for approval',
      type: 'sequential',
      agentRole: 'planner',
      modelTier: 'premium', // Plans require high reasoning
      toolScope: 'research',
      contextScope: 'full',
      requiresApproval: true,
      promptTemplate: `<role>You are a technical planner.</role>\n<context>\nApplication Context:\n{app_context}\n\nFeature Request:\n{user_request}\n</context>\n<task>\nCreate a detailed execution plan following the EPIC methodology.\n</task>\n<instructions>\nCreate a plan with:\n- Database Layer (schema changes, migrations)\n- Backend Layer (endpoints, business logic)\n- Frontend Layer (components, state)\n- TDD Strategy (list of failing tests to write)\n- Risks & Assumptions\n</instructions>`,
      timeoutMs: 60_000,
      maxRetries: 2,
    },
    {
      id: 'write-failing-tests',
      name: 'Writing and committing failing tests (TDD)',
      type: 'sequential',
      agentRole: 'test_reviewer',
      modelTier: 'standard',
      toolScope: 'implementation',
      contextScope: 'full',
      promptTemplate: `<task>\nBased on the approved plan, write the failing unit/integration tests that define the success criteria for this feature.\n</task>\n<documents>\nApproved Plan:\n{previous_output}\n</documents>\n<instructions>\nCommit these tests to the repository. Do not implement the business logic yet.\n</instructions>`,
      timeoutMs: 120_000,
      maxRetries: 1,
    },
    {
      id: 'parallel-agents',
      name: 'Implementing feature logic',
      type: 'parallel',
      agentRole: 'planner',
      modelTier: 'premium',
      toolScope: 'implementation',
      promptTemplate: 'Pass the committed tests. You are forbidden from modifying existing test files during this implementation step.',
      timeoutMs: 180_000,
      maxRetries: 2,
      branches: [
        {
          id: 'design-database',
          name: 'Database implementation',
          type: 'agent' as const,
          agentRole: 'database_agent',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
        {
          id: 'implement-backend',
          name: 'Backend implementation',
          type: 'agent' as const,
          agentRole: 'backend_agent',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
        {
          id: 'build-frontend',
          name: 'Frontend implementation',
          type: 'agent' as const,
          agentRole: 'frontend_agent',
          modelTier: 'standard',
          timeoutMs: 120_000,
        } as any,
      ],
    },
    {
      id: 'integrate-and-verify',
      name: 'Integrating and verifying',
      type: 'sequential',
      agentRole: 'fixer',
      modelTier: 'standard',
      toolScope: 'implementation',
      contextScope: 'patterns',
      promptTemplate: `Integrate the layer agent outputs and run the test suite.\n\nLayer outputs:\n{previous_output}\n\nEnsure all TDD tests now pass. If not, fix the implementation code (not the tests).`,
      timeoutMs: 120_000,
      maxRetries: 1,
    },
    {
      id: 'quality-review',
      name: 'Surgical quality review',
      type: 'sequential',
      agentRole: 'quality_reviewer',
      modelTier: 'premium',
      toolScope: 'review',
      contextScope: 'patterns',
      promptTemplate: `Run a final security and performance audit on the new feature.\n\nChanges:\n{previous_output}\n\nVerify:\n1. Zero regression on existing tests\n2. Security standard compliance\n3. Performance bottlenecks\n4. Proper error handling`,
      timeoutMs: 60_000,
      maxRetries: 1,
    },
    {
      id: 'generate-commits',
      name: 'Finalizing and committing',
      type: 'sequential',
      agentRole: 'documentarian',
      modelTier: 'free',
      toolScope: 'research',
      contextScope: 'stack',
      promptTemplate: `Generate descriptive commit messages for the completed EPIC loop.\n\nSummary of work:\n{previous_output}`,
      timeoutMs: 30000,
      maxRetries: 0,
    },
  ],
};

