/**
 * @module agent-definitions
 * @description Template for AGENTS.md at the project root.
 *   Renders a project overview, agent role table, and workflow index
 *   that AI coding agents (Copilot, Cursor, etc.) can reference.
 * @inputs ProjectModel
 * @outputs GeneratedSection[] for AGENTS.md
 * @depends-on types.ts (ProjectModel)
 * @depended-on-by file-generator.ts
 */

import type { ProjectModel } from '../../types';
import type { GeneratedSection } from '../section-manager';

export const AGENTS_MD_PATH = 'AGENTS.md';

export function generateAgentDefinitions(model: ProjectModel): GeneratedSection[] {
  const sections: GeneratedSection[] = [];

  // Project overview
  const techStack = model.getTechStack();
  const stackNames = techStack.map((e) => e.name).join(', ') || 'Not yet analyzed';
  sections.push({
    id: 'project-overview',
    content: `# Project Overview\n\nTech stack: ${stackNames}\n\nThis file is auto-generated by Roadie. It provides context for AI coding agents.`,
  });

  // Agent roles
  const roles = [
    { role: 'Diagnostician', scope: 'Bug location and root cause analysis' },
    { role: 'Fixer', scope: 'Code fixes, minimal changes, pattern-following' },
    { role: 'Planner', scope: 'Feature planning, architecture decisions' },
    { role: 'Reviewer', scope: 'Security, performance, quality, test coverage, standards' },
    { role: 'Documentarian', scope: 'Documentation generation from source code' },
  ];
  const table = [
    '| Role | Scope |',
    '|------|-------|',
    ...roles.map((r) => `| ${r.role} | ${r.scope} |`),
  ];
  sections.push({
    id: 'agent-roles',
    content: `## Agent Roles\n\n${table.join('\n')}`,
  });

  // Workflow index
  const workflows = [
    { name: 'Bug Fix', trigger: '@roadie fix ...', steps: 8 },
    { name: 'Feature', trigger: '@roadie add/create/build ...', steps: 7 },
    { name: 'Refactor', trigger: '@roadie refactor/simplify ...', steps: 5 },
    { name: 'Review', trigger: '@roadie review ...', steps: 5 },
    { name: 'Document', trigger: '@roadie document/docs ...', steps: 4 },
    { name: 'Dependency', trigger: '@roadie upgrade/migrate ...', steps: 5 },
    { name: 'Onboard', trigger: '@roadie how does/where do I start ...', steps: 4 },
  ];
  const wfTable = [
    '| Workflow | Trigger | Steps |',
    '|----------|---------|-------|',
    ...workflows.map((w) => `| ${w.name} | \`${w.trigger}\` | ${w.steps} |`),
  ];
  sections.push({
    id: 'workflows',
    content: `## Available Workflows\n\n${wfTable.join('\n')}`,
  });

  // MCP integration section
  sections.push({
    id: 'mcp-integration',
    content: [
      '## MCP Integration',
      '',
      'Roadie exposes all functionality as MCP (Model Context Protocol) tools.',
      'Add the following to your `.mcp.json` to enable Roadie in Claude Code:',
      '',
      '```json',
      '{',
      '  "mcpServers": {',
      '    "roadie": {',
      '      "command": "node",',
      '      "args": ["./node_modules/.bin/roadie-mcp", "--project", "."]',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '### Available MCP Tools',
      '',
      '| Tool | Description |',
      '|------|-------------|',
      '| `roadie/analyze_project` | Scan project structure and detect tech stack |',
      '| `roadie/get_project_context` | Return serialized context for LLM injection |',
      '| `roadie/rescan_project` | Force full re-scan |',
      '| `roadie/run_workflow` | Execute a named workflow (bug_fix, feature, etc.) |',
      '| `roadie/get_workflow_status` | Check workflow execution status |',
      '| `roadie/generate_file` | Generate a specific .github/ file |',
      '| `roadie/generate_all_files` | Regenerate all managed files |',
      '| `roadie/query_patterns` | Query detected coding patterns |',
      '| `roadie/query_workflow_history` | Retrieve past workflow outcomes |',
      '| `roadie/get_recommendations` | Get AI configuration improvement tips |',
    ].join('\n'),
  });

  return sections;
}
