/**
 * @module agent-definitions
 * @description Template for AGENTS.md at the project root.
 *   Renders a project overview, agent role table, workflow index,
 *   project commands, and directory structure for AI coding agents
 *   (Copilot, Cursor, etc.) to reference.
 *
 *   Content contract:
 *   - project-overview: always present; tech stack comma-joined
 *   - commands:         always present when commands > 0; mirrors copilot-instructions
 *   - agent-roles:      always present; 5 fixed roles (static)
 *   - workflows:        always present; 7 fixed workflows (static)
 *   - directory-structure: always present; source/test/config role assignments
 *
 * @inputs ProjectModel
 * @outputs GeneratedSection[] for AGENTS.md
 * @depends-on types.ts (ProjectModel)
 * @depended-on-by file-generator.ts
 */

import * as path from 'node:path';
import type { ProjectModel } from '../../types';
import type { GeneratedSection } from '../section-manager';
import type { LearningDatabase } from '../../learning/learning-database';

export const AGENTS_MD_PATH = 'AGENTS.md';

export function generateAgentDefinitions(model: ProjectModel, learningDb?: LearningDatabase): GeneratedSection[] {
  const sections: GeneratedSection[] = [];

  // ── Project overview ───────────────────────────────────────────────────────
  const techStack = model.getTechStack();
  const stackNames = techStack.map((e) => e.name).join(', ') || 'Not yet analyzed';
  sections.push({
    id: 'project-overview',
    content:
      `# Project Overview\n\n` +
      `**Tech stack:** ${stackNames}\n\n` +
      `This file is auto-generated by Roadie and provides context for AI coding agents.\n` +
      `Do not edit sections between \`<!-- roadie:start -->\` and \`<!-- roadie:end -->\` markers.\n` +
      `Custom notes added outside markers are preserved across regenerations.`,
  });

  // ── Project commands (required; mirrors copilot-instructions) ─────────────
  const commands = model.getCommands();
  if (commands.length > 0) {
    const lines = commands.map((c) => `- **${c.name}**: \`${c.command}\``);
    sections.push({
      id: 'commands',
      content: `## Project Commands\n\n${lines.join('\n')}`,
    });
  } else {
    sections.push({
      id: 'commands',
      content: `## Project Commands\n\n_No commands detected. Run \`roadie.rescan\` after adding scripts to package.json._`,
    });
  }

  // ── Agent roles ────────────────────────────────────────────────────────────
  const roles = [
    { role: 'Diagnostician', scope: 'Bug location and root cause analysis' },
    { role: 'Fixer',         scope: 'Code fixes, minimal changes, pattern-following' },
    { role: 'Planner',       scope: 'Feature planning, architecture decisions' },
    { role: 'Reviewer',      scope: 'Security, performance, quality, test coverage, standards' },
    { role: 'Documentarian', scope: 'Documentation generation from source code' },
  ];
  const table = [
    '| Role | Scope | Name in Dropdown |',
    '|------|-------|------------------|',
    ...roles.map((r) => `| ${r.role} | ${r.scope} | \`agent: ${r.role.toLowerCase()}\` |`),
  ];
  sections.push({
    id: 'agent-roles',
    content: `## Agent Roles\n\n${table.join('\n')}`,
  });

  // ── Workflow index ─────────────────────────────────────────────────────────
  const workflows = [
    { name: 'Bug Fix',    trigger: '@roadie fix ...',                    steps: 8 },
    { name: 'Feature',    trigger: '@roadie add/create/build ...',        steps: 7 },
    { name: 'Refactor',   trigger: '@roadie refactor/simplify ...',       steps: 5 },
    { name: 'Review',     trigger: '@roadie review ...',                  steps: 5 },
    { name: 'Document',   trigger: '@roadie document/docs ...',           steps: 4 },
    { name: 'Dependency', trigger: '@roadie upgrade/migrate ...',         steps: 5 },
    { name: 'Onboard',    trigger: '@roadie how does/where do I start ...', steps: 4 },
  ];
  const wfTable = [
    '| Workflow | Trigger | Steps |',
    '|----------|---------|-------|',
    ...workflows.map((w) => `| ${w.name} | \`${w.trigger}\` | ${w.steps} |`),
  ];
  sections.push({
    id: 'workflows',
    content: `## Available Workflows\n\n${wfTable.join('\n')}`,
  });

  // ── Directory structure ────────────────────────────────────────────────────
  const dirTree = model.getDirectoryStructure();
  const dirLines: string[] = [];

  if (dirTree) {
    const roleGroups: Record<string, string[]> = {
      source: [],
      test:   [],
      config: [],
      static: [],
      output: [],
    };

    const collectRoles = (node: typeof dirTree): void => {
      if (node.role && node.role in roleGroups) {
        roleGroups[node.role].push(path.basename(node.path));
      }
      node.children?.forEach(collectRoles);
    };
    collectRoles(dirTree);

    const labelMap: Record<string, string> = {
      source: 'Source',
      test:   'Tests',
      config: 'Config',
      static: 'Static assets',
      output: 'Build output',
    };

    for (const [role, dirs] of Object.entries(roleGroups)) {
      if (dirs.length > 0) {
        dirLines.push(`- **${labelMap[role] ?? role}:** ${dirs.join(', ')}`);
      }
    }
  }

  sections.push({
    id: 'directory-structure',
    content:
      `## Directory Structure\n\n` +
      (dirLines.length > 0
        ? dirLines.join('\n')
        : '_Directory analysis not yet run. Use `roadie.init` to scan._'),
  });

  // ── Coding standards (patterns ≥ 0.7 confidence) ──────────────────────────
  const highConfPatterns = model.getPatterns().filter((p) => p.confidence >= 0.7);
  if (highConfPatterns.length > 0) {
    const grouped: Record<string, string[]> = {};
    for (const p of highConfPatterns) {
      const g = grouped[p.category] ??= [];
      g.push(p.description);
    }
    const groups = Object.entries(grouped).map(
      ([cat, descs]) =>
        `**${cat}**\n${descs.map((d) => `- ${d}`).join('\n')}`,
    );
    sections.push({
      id: 'coding-standards',
      content: `## Coding Standards\n\n${groups.join('\n\n')}`,
    });
  }

  // ── Key files (most-edited from snapshot history) ─────────────────────────
  if (learningDb) {
    try {
      const topFiles = learningDb.getMostEditedFiles(10);
      if (topFiles.length > 0) {
        const lines = topFiles.map((f) => `- \`${f.filePath}\` (${f.editCount} edits)`);
        sections.push({
          id: 'key-files',
          content: `## Key Files\n\n_Most-edited source files from snapshot history:_\n\n${lines.join('\n')}`,
        });
      }
    } catch {
      // LearningDatabase access is non-critical
    }
  }

  // ── Learned preferences (cancellation rate + acceptance rate, visible after ≥ 5 runs) ──
  if (learningDb) {
    try {
      const cancelStats = learningDb.getWorkflowCancellationStats();
      const qualified = cancelStats.filter((s) => s.totalRuns >= 5);
      const prefLines: string[] = [];

      if (qualified.length > 0) {
        prefLines.push('_Per-workflow cancellation rates (≥ 5 runs):_');
        prefLines.push('');
        for (const s of qualified) {
          const cancelRate = ((s.cancelledRuns / s.totalRuns) * 100).toFixed(0);
          prefLines.push(`- **${s.workflowType}**: ${s.totalRuns} runs, ${cancelRate}% cancelled`);
        }
      }

      // Generation acceptance rates per file (≥ 3 transitions required)
      const allFiles = learningDb.getMostEditedFiles(20);
      const acceptanceLines: string[] = [];
      for (const { filePath } of allFiles) {
        try {
          const acc = learningDb.getGenerationAcceptanceRate(filePath);
          if (acc) {
            const pct = ((acc.accepted / (acc.accepted + acc.edited)) * 100).toFixed(0);
            const safePath = `\`${filePath.replace(/`/g, '\u200b`')}\``;
            acceptanceLines.push(`- ${safePath}: ${pct}% accepted (${acc.accepted + acc.edited} transitions)`);
          }
        } catch { /* non-critical */ }
      }

      if (acceptanceLines.length > 0) {
        if (prefLines.length > 0) prefLines.push('');
        prefLines.push('_Generation acceptance rates:_');
        prefLines.push('');
        prefLines.push(...acceptanceLines);
      }

      if (prefLines.length > 0) {
        sections.push({
          id: 'learned-preferences',
          content: `## Learned Preferences\n\n${prefLines.join('\n')}`,
        });
      }
    } catch {
      // LearningDatabase access is non-critical
    }
  }

  return sections;
}
