/**
 * @module agent-definitions
 * @description Template for AGENTS.md at the project root.
 *   Renders a project overview, agent role table, workflow index,
 *   project commands, and directory structure for AI coding agents
 *   (Copilot, Cursor, etc.) to reference.
 *
 *   Content contract:
 *   - project-overview: always present; tech stack comma-joined
 *   - commands:         always present when commands > 0; mirrors copilot-instructions
 *   - agent-roles:      always present; 5 fixed roles (static)
 *   - workflows:        always present; 7 fixed workflows (static)
 *   - directory-structure: always present; source/test/config role assignments
 *
 * @inputs ProjectModel
 * @outputs GeneratedSection[] for AGENTS.md
 * @depends-on types.ts (ProjectModel)
 * @depended-on-by file-generator.ts
 */

import * as path from 'node:path';
import type { ProjectModel, ProjectConventions } from '../../types';
import type { GeneratedSection } from '../section-manager';
import type { LearningDatabase } from '../../learning/learning-database';
import { renderConventionsString } from './template-utils';

export const AGENTS_MD_PATH = 'AGENTS.md';

export function generateAgentDefinitions(model: ProjectModel, learningDb?: LearningDatabase): GeneratedSection[] {
  const sections: GeneratedSection[] = [];

  // ── Project overview ───────────────────────────────────────────────────────
  const techStack = model.getTechStack();
  const stackNames = techStack.map((e) => e.name).join(', ') || 'Not yet analyzed';
  sections.push({
    id: 'project-overview',
    content:
      `# Project Overview\n\n` +
      `**Tech stack:** ${stackNames}\n\n` +
      `This file is auto-generated by Roadie and provides context for AI coding agents.\n` +
      `Do not edit sections between \`<!-- roadie:start -->\` and \`<!-- roadie:end -->\` markers.\n` +
      `Custom notes added outside markers are preserved across regenerations.`,
  });

  // ── Project commands (required; mirrors copilot-instructions) ─────────────
  const commands = model.getCommands();
  if (commands.length > 0) {
    const lines = commands.map((c) => `- **${c.name}**: \`${c.command}\``);
    sections.push({
      id: 'commands',
      content: `## Project Commands\n\n${lines.join('\n')}`,
    });
  } else {
    sections.push({
      id: 'commands',
      content: `## Project Commands\n\n_No commands detected. Run \`roadie.rescan\` after adding scripts to package.json._`,
    });
  }

  // ── Agent roles ────────────────────────────────────────────────────────────
  const roles = [
    { role: 'Strategist', scope: 'Orchestration, planning (Goal-Backward), and architecture' },
    { role: 'Builder',    scope: 'Core development (Interface-First), Backend, Frontend, DB' },
    { role: 'Critic',     scope: 'Quality auditing, security, and scientific code review' },
    { role: 'Delivery',   scope: 'Deployment, docs, and release integrity' },
    { role: 'Debugger',   scope: 'Scientific Debugging (Falsifiable Hypotheses)' },
  ];
  const table = [
    '| Role | Scope | Name in Dropdown |',
    '|------|-------|------------------|',
    ...roles.map((r) => `| ${r.role} | ${r.scope} | \`agent: ${r.role.toLowerCase()}\` |`),
  ];
  sections.push({
    id: 'agent-roles',
    content: `## Agent Roles\n\n${table.join('\n')}`,
  });

  // ── Workflow index ─────────────────────────────────────────────────────────
  const workflows = [
    { name: 'Bug Fix',    trigger: '@roadie fix ...',                    steps: 8 },
    { name: 'Feature',    trigger: '@roadie add/create/build ...',        steps: 7 },
    { name: 'Refactor',   trigger: '@roadie refactor/simplify ...',       steps: 5 },
    { name: 'Review',     trigger: '@roadie review ...',                  steps: 5 },
    { name: 'Document',   trigger: '@roadie document/docs ...',           steps: 4 },
    { name: 'Dependency', trigger: '@roadie upgrade/migrate ...',         steps: 5 },
    { name: 'Onboard',    trigger: '@roadie how does/where do I start ...', steps: 4 },
  ];
  const wfTable = [
    '| Workflow | Trigger | Steps | Methodology |',
    '|----------|---------|-------|-------------|',
    ...workflows.map((w) => `| ${w.name} | \`${w.trigger}\` | ${w.steps} | **EPIC** |`),
  ];
  sections.push({
    id: 'workflows',
    content: `## Available Workflows\n\n${wfTable.join('\n')}`,
  });

  // ── Core Principles (2026 Edition) ──────────────────────────────────────────
  sections.push({
    id: 'core-principles',
    content:
      `## Core Engineering Principles (Level 4 Extreme Rigor)\n\n` +
      `- **Goal-Backward Planning (Exit-Condition First):** Every task must define an **Observable Truth** before any code is written. Verbs like "improve" or "fix" are forbidden; use "Ensure X returns Y when Z".\n` +
      `- **Adversarial Red-Teaming:** Before implementing any plan, you MUST list 3 failure modes ("Why this won't work") and their associated mitigations.\n` +
      `- **Metacognitive Steering:** Every 3 turns, perform a self-audit: "Am I caught in a sunk-cost loop? Is there a simpler 'Wave 0' approach I missed?"\n` +
      `- **Interface-First (Wave 0):** Define types and exports before implementation logic.\n` +
      `- **WISC Token Hygiene (Contextual Bankruptcy):** Clean context at 80% saturation. Apply **Write-Isolate-Select-Compress** to all prompts.\n` +
      `  | Phase | Action |\n` +
      `  |-------|--------|\n` +
      `  | **Write** | Externalize memory via progress/decision logs. |\n` +
      `  | **Isolate** | Use auxiliary agents for research; return compressed summaries. |\n` +
      `  | **Select** | Load only exact files needed. Use \`.roadieignore\`. |\n` +
      `  | **Compress** | Hard-reset context at saturation limits. |\n` +
      `- **Adaptive Processing:** Economy (Low) → Standard (Med) → Quality (High) → **Max Analytics (Extreme Rigor)**.`
  });

  // ── Interaction Patterns ───────────────────────────────────────────────────
  sections.push({
    id: 'interaction-patterns',
    content:
      `## Agent Interaction Patterns\n\n` +
      `- **Writer-Reviewer:** Implementing agents are paired with an isolated Reviewer agent that audits changes for security and performance in real-time.\n` +
      `- **Competing Hypotheses:** For complex systemic bugs, multiple agents are spawned on separate worktrees testing different solutions simultaneously.\n` +
      `- **Structural Checkpoints:** All technical tasks must commit failing tests (TDD) before implementation code is authorized.`,
  });

  // ── Directory structure ────────────────────────────────────────────────────
  const dirTree = model.getDirectoryStructure();
  const dirLines: string[] = [];

  if (dirTree) {
    const roleGroups: Record<string, string[]> = {
      source: [],
      test:   [],
      config: [],
      static: [],
      output: [],
    };

    const collectRoles = (node: typeof dirTree): void => {
      if (node.role && node.role in roleGroups) {
        roleGroups[node.role].push(path.basename(node.path));
      }
      node.children?.forEach(collectRoles);
    };
    collectRoles(dirTree);

    const labelMap: Record<string, string> = {
      source: 'Source',
      test:   'Tests',
      config: 'Config',
      static: 'Static assets',
      output: 'Build output',
    };

    for (const [role, dirs] of Object.entries(roleGroups)) {
      if (dirs.length > 0) {
        dirLines.push(`- **${labelMap[role] ?? role}:** ${dirs.join(', ')}`);
      }
    }
  }

  sections.push({
    id: 'directory-structure',
    content:
      `## Directory Structure\n\n` +
      (dirLines.length > 0
        ? dirLines.join('\n')
        : '_Directory analysis not yet run. Use `roadie.init` to scan._'),
  });

  // ── Coding standards (conventions + high-confidence patterns) ──────────────
  const conv = model.getConventions();
  const convString = renderConventionsString(conv);
  
  const highConfPatterns = model.getPatterns().filter((p) => p.confidence >= 0.7);
  let patternString = '';
  if (highConfPatterns.length > 0) {
    const grouped: Record<string, string[]> = {};
    for (const p of highConfPatterns) {
      const g = grouped[p.category] ??= [];
      g.push(p.description);
    }
    patternString = Object.entries(grouped).map(
      ([cat, descs]) =>
        `**${cat}**\n${descs.map((d) => `- ${d}`).join('\n')}`,
    ).join('\n\n');
  }

  if (convString || patternString) {
    const content = [
      convString,
      patternString ? `### Detected Patterns\n\n${patternString}` : ''
    ].filter(Boolean).join('\n\n');

    sections.push({
      id: 'coding-standards',
      content: `## Coding Standards\n\n${content}`,
    });
  }

  // ── Key files (most-edited from snapshot history) ─────────────────────────
  if (learningDb) {
    try {
      const topFiles = learningDb.getMostEditedFiles(10);
      if (topFiles.length > 0) {
        const lines = topFiles.map((f) => `- \`${f.filePath}\` (${f.editCount} edits)`);
        sections.push({
          id: 'key-files',
          content: `## Key Files\n\n_Most-edited source files from snapshot history:_\n\n${lines.join('\n')}`,
        });
      }
    } catch {
      // LearningDatabase access is non-critical
    }
  }

  // ── Learned preferences (cancellation rate + acceptance rate, visible after ≥ 5 runs) ──
  if (learningDb) {
    try {
      const cancelStats = learningDb.getWorkflowCancellationStats();
      const qualified = cancelStats.filter((s) => s.totalRuns >= 5);
      const prefLines: string[] = [];

      if (qualified.length > 0) {
        prefLines.push('_Per-workflow cancellation rates (≥ 5 runs):_');
        prefLines.push('');
        for (const s of qualified) {
          const cancelRate = ((s.cancelledRuns / s.totalRuns) * 100).toFixed(0);
          prefLines.push(`- **${s.workflowType}**: ${s.totalRuns} runs, ${cancelRate}% cancelled`);
        }
      }

      // Generation acceptance rates per file (≥ 3 transitions required)
      const allFiles = learningDb.getMostEditedFiles(20);
      const acceptanceLines: string[] = [];
      for (const { filePath } of allFiles) {
        try {
          const acc = learningDb.getGenerationAcceptanceRate(filePath);
          if (acc) {
            const pct = ((acc.accepted / (acc.accepted + acc.edited)) * 100).toFixed(0);
            const safePath = `\`${filePath.replace(/`/g, '\u200b`')}\``;
            acceptanceLines.push(`- ${safePath}: ${pct}% accepted (${acc.accepted + acc.edited} transitions)`);
          }
        } catch { /* non-critical */ }
      }

      if (acceptanceLines.length > 0) {
        if (prefLines.length > 0) prefLines.push('');
        prefLines.push('_Generation acceptance rates:_');
        prefLines.push('');
        prefLines.push(...acceptanceLines);
      }

      if (prefLines.length > 0) {
        sections.push({
          id: 'learned-preferences',
          content: `## Learned Preferences\n\n${prefLines.join('\n')}`,
        });
      }
    } catch {
      // LearningDatabase access is non-critical
    }
  }

  return sections;
}
