/**
 * @module copilot-instructions
 * @description Template for .github/copilot-instructions.md.
 *   Renders tech stack, package manager, test/build/dev commands,
 *   and detected patterns into a markdown file that GitHub Copilot
 *   reads for project-specific context.
 * @inputs ProjectModel
 * @outputs GeneratedSection[] for copilot-instructions.md
 * @depends-on types.ts (ProjectModel)
 * @depended-on-by file-generator.ts
 */

import * as path from 'node:path';
import type { ProjectModel } from '../../types';
import type { GeneratedSection } from '../section-manager';
import { renderConventionsString } from './template-utils';

export const COPILOT_INSTRUCTIONS_PATH = '.github/copilot-instructions.md';

export function generateCopilotInstructions(model: ProjectModel, options?: { simplified?: boolean }): GeneratedSection[] {
  const sections: GeneratedSection[] = [];

  const conventions = model.getConventions();
  const convString = renderConventionsString(conventions);
  if (convString) {
    sections.push({
      id: 'custom-conventions',
      content: `## Project Conventions\n\n${convString}`,
    });
  }

  // Project overview section
  const techStack = model.getTechStack();
  const stackNames = techStack.map((e) => e.name).join(', ') || 'Not yet analyzed';
  sections.push({
    id: 'project-overview',
    content: `## Project Overview\n\nTech stack: ${stackNames}\n\nThis file is auto-generated by Roadie. It provides context for AI coding agents.\n`,
  });

  // Tech stack section
  if (techStack.length > 0) {
    const lines = techStack.map((e) => {
      const ver = e.version ? ` ${e.version}` : '';
      return `- **${e.name}**${ver} (${e.category})`;
    });
    sections.push({
      id: 'tech-stack',
      content: `## Tech Stack\n\n${lines.join('\n')}`,
    });
  }

  // Commands section
  const commands = model.getCommands();
  if (commands.length > 0) {
    const lines = commands.map((c) => `- **${c.name}**: \`${c.command}\``);
    sections.push({
      id: 'commands',
      content: `## Project Commands\n\n${lines.join('\n')}`,
    });
  }

  // Simplified mode: drop project-structure and patterns
  if (options?.simplified) {
    return sections;
  }

  // Project structure section
  const dirTree = model.getDirectoryStructure();
  if (dirTree?.children && dirTree.children.length > 0) {
    const structLines = dirTree.children
      .filter((c) => c.type === 'directory')
      .map((c) => {
        const name = path.basename(c.path);
        const role = c.role ? ` (${c.role})` : '';
        return `- **${name}/**${role}`;
      });
    if (structLines.length > 0) {
      sections.push({
        id: 'project-structure',
        content: `## Project Structure\n\n${structLines.join('\n')}`,
      });
    }
  }

  // Patterns section
  const patterns = model.getPatterns();
  if (patterns.length > 0) {
    const lines = patterns
      .filter((p) => p.confidence >= 0.7)
      .map((p) => `- ${p.description}`);
    if (lines.length > 0) {
      sections.push({
        id: 'patterns',
        content: `## Code Conventions\n\n${lines.join('\n')}`,
      });
    }
  }

  return sections;
}
